sudo: required
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa
- sudo apt-get update
- sudo apt-get -y install cgi-mapserver
install: 
- pip install tox-travis
- python setup.py install
script: tox
