sudo: required
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa
- sudo apt-get update
- sudo apt-get -y install cgi-mapserver
- echo "$TRAVIS_BUILD_DIR"
- git clone https://github.com/mapserver/mapserver.git
- echo "$TRAVIS_BUILD_DIR"/mapserver
- ln -s "$TRAVIS_BUILD_DIR"/mapserver "$TRAVIS_BUILD_DIR"/mappyscript/src
- cp "$TRAVIS_BUILD_DIR"/mapserver-config.h.in "$TRAVIS_BUILD_DIR"/mapserver-config.h
install: 
- pip install tox-travis
- python setup.py install
script: tox
